-- CREATE TABLE public.user_role (
--   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name text NOT NULL
-- );

-- -- Add default values
-- INSERT INTO public.user_role (name) VALUES ('User'), ('Startup');

-- -- Add RLS policy
-- ALTER TABLE public.user_role ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY "select_user_role_public"
-- ON public.user_role
-- AS PERMISSIVE
-- FOR SELECT
-- TO public
-- USING (true);

-- -- Add foreign key to profiles (if you want to link them)
-- ALTER TABLE profiles ADD COLUMN user_type_id integer REFERENCES public.user_role(id);

-- -- Grant permissions
-- GRANT SELECT ON TABLE public.user_role TO anon, authenticated, service_role;
