-- CREATE TABLE public.user_types (
--   id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name text NOT NULL
-- );

-- -- Add default values
-- INSERT INTO public.user_types (name) VALUES ('User'), ('Startup');

-- -- Add RLS policy
-- ALTER TABLE public.user_types ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY "select_user_types_public"
-- ON public.user_types
-- AS PERMISSIVE
-- FOR SELECT
-- TO public
-- USING (true);

-- -- Add foreign key to profiles (if you want to link them)
-- ALTER TABLE profiles ADD COLUMN user_type_id integer REFERENCES public.user_types(id);

-- -- Grant permissions
-- GRANT SELECT ON TABLE public.user_types TO anon, authenticated, service_role;
